
client.caches.db
CREATE TABLE file_maintenance_jobs ( hash_id INTEGER, job_type INTEGER, time_can_start INTEGER, PRIMARY KEY ( hash_id, job_type ) );
CREATE TABLE shape_perceptual_hashes ( phash_id INTEGER PRIMARY KEY, phash BLOB_BYTES UNIQUE );
CREATE TABLE shape_perceptual_hash_map ( phash_id INTEGER, hash_id INTEGER, PRIMARY KEY ( phash_id, hash_id ) );
CREATE TABLE shape_vptree ( phash_id INTEGER PRIMARY KEY, parent_id INTEGER, radius INTEGER, inner_id INTEGER, inner_population INTEGER, outer_id INTEGER, outer_population INTEGER );
CREATE TABLE shape_maintenance_branch_regen ( phash_id INTEGER PRIMARY KEY );
CREATE TABLE IF NOT EXISTS 'notes_fts4_content'(docid INTEGER PRIMARY KEY, 'c0note');
CREATE TABLE IF NOT EXISTS 'notes_fts4_segments'(blockid INTEGER PRIMARY KEY, block BLOB);
CREATE TABLE IF NOT EXISTS 'notes_fts4_segdir'(level INTEGER,idx INTEGER,start_block INTEGER,leaves_end_block INTEGER,end_block INTEGER,root BLOB,PRIMARY KEY(level, idx));
CREATE TABLE IF NOT EXISTS 'notes_fts4_docsize'(docid INTEGER PRIMARY KEY, size BLOB);
CREATE TABLE IF NOT EXISTS 'notes_fts4_stat'(id INTEGER PRIMARY KEY, value BLOB);
CREATE TABLE shape_search_cache ( hash_id INTEGER PRIMARY KEY, searched_distance INTEGER );
CREATE TABLE local_tags_cache ( tag_id INTEGER PRIMARY KEY, tag TEXT UNIQUE );
CREATE TABLE sqlite_stat1(tbl,idx,stat);
CREATE TABLE combined_files_ac_cache_7 ( tag_id INTEGER PRIMARY KEY, current_count INTEGER, pending_count INTEGER );
CREATE TABLE specific_files_cache_3_7 ( hash_id INTEGER PRIMARY KEY );
CREATE TABLE specific_current_mappings_cache_3_7 ( hash_id INTEGER, tag_id INTEGER, PRIMARY KEY ( hash_id, tag_id ) ) WITHOUT ROWID;
CREATE TABLE specific_deleted_mappings_cache_3_7 ( hash_id INTEGER, tag_id INTEGER, PRIMARY KEY ( hash_id, tag_id ) ) WITHOUT ROWID;
CREATE TABLE specific_pending_mappings_cache_3_7 ( hash_id INTEGER, tag_id INTEGER, PRIMARY KEY ( hash_id, tag_id ) ) WITHOUT ROWID;
CREATE TABLE specific_ac_cache_3_7 ( tag_id INTEGER PRIMARY KEY, current_count INTEGER, pending_count INTEGER );
CREATE TABLE specific_files_cache_4_7 ( hash_id INTEGER PRIMARY KEY );
CREATE TABLE specific_current_mappings_cache_4_7 ( hash_id INTEGER, tag_id INTEGER, PRIMARY KEY ( hash_id, tag_id ) ) WITHOUT ROWID;
CREATE TABLE specific_deleted_mappings_cache_4_7 ( hash_id INTEGER, tag_id INTEGER, PRIMARY KEY ( hash_id, tag_id ) ) WITHOUT ROWID;
CREATE TABLE specific_pending_mappings_cache_4_7 ( hash_id INTEGER, tag_id INTEGER, PRIMARY KEY ( hash_id, tag_id ) ) WITHOUT ROWID;
CREATE TABLE specific_ac_cache_4_7 ( tag_id INTEGER PRIMARY KEY, current_count INTEGER, pending_count INTEGER );
CREATE TABLE specific_files_cache_5_7 ( hash_id INTEGER PRIMARY KEY );
CREATE TABLE specific_current_mappings_cache_5_7 ( hash_id INTEGER, tag_id INTEGER, PRIMARY KEY ( hash_id, tag_id ) ) WITHOUT ROWID;
CREATE TABLE specific_deleted_mappings_cache_5_7 ( hash_id INTEGER, tag_id INTEGER, PRIMARY KEY ( hash_id, tag_id ) ) WITHOUT ROWID;
CREATE TABLE specific_pending_mappings_cache_5_7 ( hash_id INTEGER, tag_id INTEGER, PRIMARY KEY ( hash_id, tag_id ) ) WITHOUT ROWID;
CREATE TABLE specific_ac_cache_5_7 ( tag_id INTEGER PRIMARY KEY, current_count INTEGER, pending_count INTEGER );
CREATE TABLE specific_files_cache_6_7 ( hash_id INTEGER PRIMARY KEY );
CREATE TABLE specific_current_mappings_cache_6_7 ( hash_id INTEGER, tag_id INTEGER, PRIMARY KEY ( hash_id, tag_id ) ) WITHOUT ROWID;
CREATE TABLE specific_deleted_mappings_cache_6_7 ( hash_id INTEGER, tag_id INTEGER, PRIMARY KEY ( hash_id, tag_id ) ) WITHOUT ROWID;
CREATE TABLE specific_pending_mappings_cache_6_7 ( hash_id INTEGER, tag_id INTEGER, PRIMARY KEY ( hash_id, tag_id ) ) WITHOUT ROWID;
CREATE TABLE specific_ac_cache_6_7 ( tag_id INTEGER PRIMARY KEY, current_count INTEGER, pending_count INTEGER );
CREATE TABLE specific_display_ac_cache_3_7 ( tag_id INTEGER PRIMARY KEY, current_count INTEGER, pending_count INTEGER );
CREATE TABLE specific_display_current_mappings_cache_3_7 ( hash_id INTEGER, tag_id INTEGER, PRIMARY KEY ( hash_id, tag_id ) ) WITHOUT ROWID;
CREATE TABLE specific_display_pending_mappings_cache_3_7 ( hash_id INTEGER, tag_id INTEGER, PRIMARY KEY ( hash_id, tag_id ) ) WITHOUT ROWID;
CREATE TABLE specific_display_ac_cache_4_7 ( tag_id INTEGER PRIMARY KEY, current_count INTEGER, pending_count INTEGER );
CREATE TABLE specific_display_current_mappings_cache_4_7 ( hash_id INTEGER, tag_id INTEGER, PRIMARY KEY ( hash_id, tag_id ) ) WITHOUT ROWID;
CREATE TABLE specific_display_pending_mappings_cache_4_7 ( hash_id INTEGER, tag_id INTEGER, PRIMARY KEY ( hash_id, tag_id ) ) WITHOUT ROWID;
CREATE TABLE specific_display_ac_cache_5_7 ( tag_id INTEGER PRIMARY KEY, current_count INTEGER, pending_count INTEGER );
CREATE TABLE specific_display_current_mappings_cache_5_7 ( hash_id INTEGER, tag_id INTEGER, PRIMARY KEY ( hash_id, tag_id ) ) WITHOUT ROWID;
CREATE TABLE specific_display_pending_mappings_cache_5_7 ( hash_id INTEGER, tag_id INTEGER, PRIMARY KEY ( hash_id, tag_id ) ) WITHOUT ROWID;
CREATE TABLE specific_display_ac_cache_6_7 ( tag_id INTEGER PRIMARY KEY, current_count INTEGER, pending_count INTEGER );
CREATE TABLE specific_display_current_mappings_cache_6_7 ( hash_id INTEGER, tag_id INTEGER, PRIMARY KEY ( hash_id, tag_id ) ) WITHOUT ROWID;
CREATE TABLE specific_display_pending_mappings_cache_6_7 ( hash_id INTEGER, tag_id INTEGER, PRIMARY KEY ( hash_id, tag_id ) ) WITHOUT ROWID;
CREATE TABLE combined_files_display_ac_cache_7 ( tag_id INTEGER PRIMARY KEY, current_count INTEGER, pending_count INTEGER );
CREATE TABLE actual_tag_siblings_lookup_cache_7 ( bad_tag_id INTEGER PRIMARY KEY, ideal_tag_id INTEGER );
CREATE TABLE ideal_tag_siblings_lookup_cache_7 ( bad_tag_id INTEGER PRIMARY KEY, ideal_tag_id INTEGER );
CREATE TABLE actual_tag_parents_lookup_cache_7 ( child_tag_id INTEGER, ancestor_tag_id INTEGER, PRIMARY KEY ( child_tag_id, ancestor_tag_id ) );
CREATE TABLE ideal_tag_parents_lookup_cache_7 ( child_tag_id INTEGER, ancestor_tag_id INTEGER, PRIMARY KEY ( child_tag_id, ancestor_tag_id ) );
CREATE INDEX shape_perceptual_hash_map_hash_id_index ON shape_perceptual_hash_map (hash_id);
CREATE INDEX shape_vptree_parent_id_index ON shape_vptree (parent_id);
CREATE UNIQUE INDEX specific_current_mappings_cache_3_7_tag_id_hash_id_index ON specific_current_mappings_cache_3_7 (tag_id, hash_id);
CREATE UNIQUE INDEX specific_deleted_mappings_cache_3_7_tag_id_hash_id_index ON specific_deleted_mappings_cache_3_7 (tag_id, hash_id);
CREATE UNIQUE INDEX specific_pending_mappings_cache_3_7_tag_id_hash_id_index ON specific_pending_mappings_cache_3_7 (tag_id, hash_id);
CREATE UNIQUE INDEX specific_current_mappings_cache_4_7_tag_id_hash_id_index ON specific_current_mappings_cache_4_7 (tag_id, hash_id);
CREATE UNIQUE INDEX specific_deleted_mappings_cache_4_7_tag_id_hash_id_index ON specific_deleted_mappings_cache_4_7 (tag_id, hash_id);
CREATE UNIQUE INDEX specific_pending_mappings_cache_4_7_tag_id_hash_id_index ON specific_pending_mappings_cache_4_7 (tag_id, hash_id);
CREATE UNIQUE INDEX specific_current_mappings_cache_5_7_tag_id_hash_id_index ON specific_current_mappings_cache_5_7 (tag_id, hash_id);
CREATE UNIQUE INDEX specific_deleted_mappings_cache_5_7_tag_id_hash_id_index ON specific_deleted_mappings_cache_5_7 (tag_id, hash_id);
CREATE UNIQUE INDEX specific_pending_mappings_cache_5_7_tag_id_hash_id_index ON specific_pending_mappings_cache_5_7 (tag_id, hash_id);
CREATE UNIQUE INDEX specific_current_mappings_cache_6_7_tag_id_hash_id_index ON specific_current_mappings_cache_6_7 (tag_id, hash_id);
CREATE UNIQUE INDEX specific_deleted_mappings_cache_6_7_tag_id_hash_id_index ON specific_deleted_mappings_cache_6_7 (tag_id, hash_id);
CREATE UNIQUE INDEX specific_pending_mappings_cache_6_7_tag_id_hash_id_index ON specific_pending_mappings_cache_6_7 (tag_id, hash_id);
CREATE UNIQUE INDEX specific_display_current_mappings_cache_3_7_tag_id_hash_id_index ON specific_display_current_mappings_cache_3_7 (tag_id, hash_id);
CREATE UNIQUE INDEX specific_display_pending_mappings_cache_3_7_tag_id_hash_id_index ON specific_display_pending_mappings_cache_3_7 (tag_id, hash_id);
CREATE UNIQUE INDEX specific_display_current_mappings_cache_4_7_tag_id_hash_id_index ON specific_display_current_mappings_cache_4_7 (tag_id, hash_id);
CREATE UNIQUE INDEX specific_display_pending_mappings_cache_4_7_tag_id_hash_id_index ON specific_display_pending_mappings_cache_4_7 (tag_id, hash_id);
CREATE UNIQUE INDEX specific_display_current_mappings_cache_5_7_tag_id_hash_id_index ON specific_display_current_mappings_cache_5_7 (tag_id, hash_id);
CREATE UNIQUE INDEX specific_display_pending_mappings_cache_5_7_tag_id_hash_id_index ON specific_display_pending_mappings_cache_5_7 (tag_id, hash_id);
CREATE UNIQUE INDEX specific_display_current_mappings_cache_6_7_tag_id_hash_id_index ON specific_display_current_mappings_cache_6_7 (tag_id, hash_id);
CREATE UNIQUE INDEX specific_display_pending_mappings_cache_6_7_tag_id_hash_id_index ON specific_display_pending_mappings_cache_6_7 (tag_id, hash_id);
CREATE INDEX actual_tag_siblings_lookup_cache_7_ideal_tag_id_index ON actual_tag_siblings_lookup_cache_7 (ideal_tag_id);
CREATE INDEX ideal_tag_siblings_lookup_cache_7_ideal_tag_id_index ON ideal_tag_siblings_lookup_cache_7 (ideal_tag_id);
CREATE INDEX actual_tag_parents_lookup_cache_7_ancestor_tag_id_index ON actual_tag_parents_lookup_cache_7 (ancestor_tag_id);
CREATE INDEX ideal_tag_parents_lookup_cache_7_ancestor_tag_id_index ON ideal_tag_parents_lookup_cache_7 (ancestor_tag_id);
CREATE VIRTUAL TABLE notes_fts4 USING fts4( note )
/* notes_fts4(note) */;
CREATE TABLE local_hashes_cache ( hash_id INTEGER PRIMARY KEY, hash BLOB_BYTES UNIQUE );
CREATE TABLE specific_files_cache_13_7 ( hash_id INTEGER PRIMARY KEY );
CREATE TABLE specific_ac_cache_13_7 ( tag_id INTEGER PRIMARY KEY, current_count INTEGER, pending_count INTEGER );
CREATE TABLE specific_current_mappings_cache_13_7 ( hash_id INTEGER, tag_id INTEGER, PRIMARY KEY ( hash_id, tag_id ) ) WITHOUT ROWID;
CREATE TABLE specific_deleted_mappings_cache_13_7 ( hash_id INTEGER, tag_id INTEGER, PRIMARY KEY ( hash_id, tag_id ) ) WITHOUT ROWID;
CREATE TABLE specific_pending_mappings_cache_13_7 ( hash_id INTEGER, tag_id INTEGER, PRIMARY KEY ( hash_id, tag_id ) ) WITHOUT ROWID;
CREATE UNIQUE INDEX specific_current_mappings_cache_13_7_tag_id_hash_id_index ON specific_current_mappings_cache_13_7 (tag_id, hash_id);
CREATE UNIQUE INDEX specific_deleted_mappings_cache_13_7_tag_id_hash_id_index ON specific_deleted_mappings_cache_13_7 (tag_id, hash_id);
CREATE UNIQUE INDEX specific_pending_mappings_cache_13_7_tag_id_hash_id_index ON specific_pending_mappings_cache_13_7 (tag_id, hash_id);
CREATE TABLE specific_display_ac_cache_13_7 ( tag_id INTEGER PRIMARY KEY, current_count INTEGER, pending_count INTEGER );
CREATE TABLE specific_display_current_mappings_cache_13_7 ( hash_id INTEGER, tag_id INTEGER, PRIMARY KEY ( hash_id, tag_id ) ) WITHOUT ROWID;
CREATE TABLE specific_display_pending_mappings_cache_13_7 ( hash_id INTEGER, tag_id INTEGER, PRIMARY KEY ( hash_id, tag_id ) ) WITHOUT ROWID;
CREATE UNIQUE INDEX specific_display_current_mappings_cache_13_7_tag_id_hash_id_index ON specific_display_current_mappings_cache_13_7 (tag_id, hash_id);
CREATE UNIQUE INDEX specific_display_pending_mappings_cache_13_7_tag_id_hash_id_index ON specific_display_pending_mappings_cache_13_7 (tag_id, hash_id);
CREATE TABLE actual_tag_siblings_lookup_cache_14 ( bad_tag_id INTEGER PRIMARY KEY, ideal_tag_id INTEGER );
CREATE TABLE ideal_tag_siblings_lookup_cache_14 ( bad_tag_id INTEGER PRIMARY KEY, ideal_tag_id INTEGER );
CREATE INDEX actual_tag_siblings_lookup_cache_14_ideal_tag_id_index ON actual_tag_siblings_lookup_cache_14 (ideal_tag_id);
CREATE INDEX ideal_tag_siblings_lookup_cache_14_ideal_tag_id_index ON ideal_tag_siblings_lookup_cache_14 (ideal_tag_id);
CREATE TABLE actual_tag_parents_lookup_cache_14 ( child_tag_id INTEGER, ancestor_tag_id INTEGER, PRIMARY KEY ( child_tag_id, ancestor_tag_id ) );
CREATE TABLE ideal_tag_parents_lookup_cache_14 ( child_tag_id INTEGER, ancestor_tag_id INTEGER, PRIMARY KEY ( child_tag_id, ancestor_tag_id ) );
CREATE INDEX actual_tag_parents_lookup_cache_14_ancestor_tag_id_index ON actual_tag_parents_lookup_cache_14 (ancestor_tag_id);
CREATE INDEX ideal_tag_parents_lookup_cache_14_ancestor_tag_id_index ON ideal_tag_parents_lookup_cache_14 (ancestor_tag_id);
CREATE TABLE combined_files_ac_cache_14 ( tag_id INTEGER PRIMARY KEY, current_count INTEGER, pending_count INTEGER );
CREATE TABLE combined_files_display_ac_cache_14 ( tag_id INTEGER PRIMARY KEY, current_count INTEGER, pending_count INTEGER );
CREATE TABLE specific_files_cache_3_14 ( hash_id INTEGER PRIMARY KEY );
CREATE TABLE specific_ac_cache_3_14 ( tag_id INTEGER PRIMARY KEY, current_count INTEGER, pending_count INTEGER );
CREATE TABLE specific_current_mappings_cache_3_14 ( hash_id INTEGER, tag_id INTEGER, PRIMARY KEY ( hash_id, tag_id ) ) WITHOUT ROWID;
CREATE TABLE specific_deleted_mappings_cache_3_14 ( hash_id INTEGER, tag_id INTEGER, PRIMARY KEY ( hash_id, tag_id ) ) WITHOUT ROWID;
CREATE TABLE specific_pending_mappings_cache_3_14 ( hash_id INTEGER, tag_id INTEGER, PRIMARY KEY ( hash_id, tag_id ) ) WITHOUT ROWID;
CREATE UNIQUE INDEX specific_current_mappings_cache_3_14_tag_id_hash_id_index ON specific_current_mappings_cache_3_14 (tag_id, hash_id);
CREATE UNIQUE INDEX specific_deleted_mappings_cache_3_14_tag_id_hash_id_index ON specific_deleted_mappings_cache_3_14 (tag_id, hash_id);
CREATE UNIQUE INDEX specific_pending_mappings_cache_3_14_tag_id_hash_id_index ON specific_pending_mappings_cache_3_14 (tag_id, hash_id);
CREATE TABLE specific_display_ac_cache_3_14 ( tag_id INTEGER PRIMARY KEY, current_count INTEGER, pending_count INTEGER );
CREATE TABLE specific_display_current_mappings_cache_3_14 ( hash_id INTEGER, tag_id INTEGER, PRIMARY KEY ( hash_id, tag_id ) ) WITHOUT ROWID;
CREATE TABLE specific_display_pending_mappings_cache_3_14 ( hash_id INTEGER, tag_id INTEGER, PRIMARY KEY ( hash_id, tag_id ) ) WITHOUT ROWID;
CREATE UNIQUE INDEX specific_display_current_mappings_cache_3_14_tag_id_hash_id_index ON specific_display_current_mappings_cache_3_14 (tag_id, hash_id);
CREATE UNIQUE INDEX specific_display_pending_mappings_cache_3_14_tag_id_hash_id_index ON specific_display_pending_mappings_cache_3_14 (tag_id, hash_id);
CREATE TABLE specific_files_cache_4_14 ( hash_id INTEGER PRIMARY KEY );
CREATE TABLE specific_ac_cache_4_14 ( tag_id INTEGER PRIMARY KEY, current_count INTEGER, pending_count INTEGER );
CREATE TABLE specific_current_mappings_cache_4_14 ( hash_id INTEGER, tag_id INTEGER, PRIMARY KEY ( hash_id, tag_id ) ) WITHOUT ROWID;
CREATE TABLE specific_deleted_mappings_cache_4_14 ( hash_id INTEGER, tag_id INTEGER, PRIMARY KEY ( hash_id, tag_id ) ) WITHOUT ROWID;
CREATE TABLE specific_pending_mappings_cache_4_14 ( hash_id INTEGER, tag_id INTEGER, PRIMARY KEY ( hash_id, tag_id ) ) WITHOUT ROWID;
CREATE UNIQUE INDEX specific_current_mappings_cache_4_14_tag_id_hash_id_index ON specific_current_mappings_cache_4_14 (tag_id, hash_id);
CREATE UNIQUE INDEX specific_deleted_mappings_cache_4_14_tag_id_hash_id_index ON specific_deleted_mappings_cache_4_14 (tag_id, hash_id);
CREATE UNIQUE INDEX specific_pending_mappings_cache_4_14_tag_id_hash_id_index ON specific_pending_mappings_cache_4_14 (tag_id, hash_id);
CREATE TABLE specific_display_ac_cache_4_14 ( tag_id INTEGER PRIMARY KEY, current_count INTEGER, pending_count INTEGER );
CREATE TABLE specific_display_current_mappings_cache_4_14 ( hash_id INTEGER, tag_id INTEGER, PRIMARY KEY ( hash_id, tag_id ) ) WITHOUT ROWID;
CREATE TABLE specific_display_pending_mappings_cache_4_14 ( hash_id INTEGER, tag_id INTEGER, PRIMARY KEY ( hash_id, tag_id ) ) WITHOUT ROWID;
CREATE UNIQUE INDEX specific_display_current_mappings_cache_4_14_tag_id_hash_id_index ON specific_display_current_mappings_cache_4_14 (tag_id, hash_id);
CREATE UNIQUE INDEX specific_display_pending_mappings_cache_4_14_tag_id_hash_id_index ON specific_display_pending_mappings_cache_4_14 (tag_id, hash_id);
CREATE TABLE specific_files_cache_5_14 ( hash_id INTEGER PRIMARY KEY );
CREATE TABLE specific_ac_cache_5_14 ( tag_id INTEGER PRIMARY KEY, current_count INTEGER, pending_count INTEGER );
CREATE TABLE specific_current_mappings_cache_5_14 ( hash_id INTEGER, tag_id INTEGER, PRIMARY KEY ( hash_id, tag_id ) ) WITHOUT ROWID;
CREATE TABLE specific_deleted_mappings_cache_5_14 ( hash_id INTEGER, tag_id INTEGER, PRIMARY KEY ( hash_id, tag_id ) ) WITHOUT ROWID;
CREATE TABLE specific_pending_mappings_cache_5_14 ( hash_id INTEGER, tag_id INTEGER, PRIMARY KEY ( hash_id, tag_id ) ) WITHOUT ROWID;
CREATE UNIQUE INDEX specific_current_mappings_cache_5_14_tag_id_hash_id_index ON specific_current_mappings_cache_5_14 (tag_id, hash_id);
CREATE UNIQUE INDEX specific_deleted_mappings_cache_5_14_tag_id_hash_id_index ON specific_deleted_mappings_cache_5_14 (tag_id, hash_id);
CREATE UNIQUE INDEX specific_pending_mappings_cache_5_14_tag_id_hash_id_index ON specific_pending_mappings_cache_5_14 (tag_id, hash_id);
CREATE TABLE specific_display_ac_cache_5_14 ( tag_id INTEGER PRIMARY KEY, current_count INTEGER, pending_count INTEGER );
CREATE TABLE specific_display_current_mappings_cache_5_14 ( hash_id INTEGER, tag_id INTEGER, PRIMARY KEY ( hash_id, tag_id ) ) WITHOUT ROWID;
CREATE TABLE specific_display_pending_mappings_cache_5_14 ( hash_id INTEGER, tag_id INTEGER, PRIMARY KEY ( hash_id, tag_id ) ) WITHOUT ROWID;
CREATE UNIQUE INDEX specific_display_current_mappings_cache_5_14_tag_id_hash_id_index ON specific_display_current_mappings_cache_5_14 (tag_id, hash_id);
CREATE UNIQUE INDEX specific_display_pending_mappings_cache_5_14_tag_id_hash_id_index ON specific_display_pending_mappings_cache_5_14 (tag_id, hash_id);
CREATE TABLE specific_files_cache_6_14 ( hash_id INTEGER PRIMARY KEY );
CREATE TABLE specific_ac_cache_6_14 ( tag_id INTEGER PRIMARY KEY, current_count INTEGER, pending_count INTEGER );
CREATE TABLE specific_current_mappings_cache_6_14 ( hash_id INTEGER, tag_id INTEGER, PRIMARY KEY ( hash_id, tag_id ) ) WITHOUT ROWID;
CREATE TABLE specific_deleted_mappings_cache_6_14 ( hash_id INTEGER, tag_id INTEGER, PRIMARY KEY ( hash_id, tag_id ) ) WITHOUT ROWID;
CREATE TABLE specific_pending_mappings_cache_6_14 ( hash_id INTEGER, tag_id INTEGER, PRIMARY KEY ( hash_id, tag_id ) ) WITHOUT ROWID;
CREATE UNIQUE INDEX specific_current_mappings_cache_6_14_tag_id_hash_id_index ON specific_current_mappings_cache_6_14 (tag_id, hash_id);
CREATE UNIQUE INDEX specific_deleted_mappings_cache_6_14_tag_id_hash_id_index ON specific_deleted_mappings_cache_6_14 (tag_id, hash_id);
CREATE UNIQUE INDEX specific_pending_mappings_cache_6_14_tag_id_hash_id_index ON specific_pending_mappings_cache_6_14 (tag_id, hash_id);
CREATE TABLE specific_display_ac_cache_6_14 ( tag_id INTEGER PRIMARY KEY, current_count INTEGER, pending_count INTEGER );
CREATE TABLE specific_display_current_mappings_cache_6_14 ( hash_id INTEGER, tag_id INTEGER, PRIMARY KEY ( hash_id, tag_id ) ) WITHOUT ROWID;
CREATE TABLE specific_display_pending_mappings_cache_6_14 ( hash_id INTEGER, tag_id INTEGER, PRIMARY KEY ( hash_id, tag_id ) ) WITHOUT ROWID;
CREATE UNIQUE INDEX specific_display_current_mappings_cache_6_14_tag_id_hash_id_index ON specific_display_current_mappings_cache_6_14 (tag_id, hash_id);
CREATE UNIQUE INDEX specific_display_pending_mappings_cache_6_14_tag_id_hash_id_index ON specific_display_pending_mappings_cache_6_14 (tag_id, hash_id);
CREATE TABLE specific_files_cache_13_14 ( hash_id INTEGER PRIMARY KEY );
CREATE TABLE specific_ac_cache_13_14 ( tag_id INTEGER PRIMARY KEY, current_count INTEGER, pending_count INTEGER );
CREATE TABLE specific_current_mappings_cache_13_14 ( hash_id INTEGER, tag_id INTEGER, PRIMARY KEY ( hash_id, tag_id ) ) WITHOUT ROWID;
CREATE TABLE specific_deleted_mappings_cache_13_14 ( hash_id INTEGER, tag_id INTEGER, PRIMARY KEY ( hash_id, tag_id ) ) WITHOUT ROWID;
CREATE TABLE specific_pending_mappings_cache_13_14 ( hash_id INTEGER, tag_id INTEGER, PRIMARY KEY ( hash_id, tag_id ) ) WITHOUT ROWID;
CREATE UNIQUE INDEX specific_current_mappings_cache_13_14_tag_id_hash_id_index ON specific_current_mappings_cache_13_14 (tag_id, hash_id);
CREATE UNIQUE INDEX specific_deleted_mappings_cache_13_14_tag_id_hash_id_index ON specific_deleted_mappings_cache_13_14 (tag_id, hash_id);
CREATE UNIQUE INDEX specific_pending_mappings_cache_13_14_tag_id_hash_id_index ON specific_pending_mappings_cache_13_14 (tag_id, hash_id);
CREATE TABLE specific_display_ac_cache_13_14 ( tag_id INTEGER PRIMARY KEY, current_count INTEGER, pending_count INTEGER );
CREATE TABLE specific_display_current_mappings_cache_13_14 ( hash_id INTEGER, tag_id INTEGER, PRIMARY KEY ( hash_id, tag_id ) ) WITHOUT ROWID;
CREATE TABLE specific_display_pending_mappings_cache_13_14 ( hash_id INTEGER, tag_id INTEGER, PRIMARY KEY ( hash_id, tag_id ) ) WITHOUT ROWID;
CREATE UNIQUE INDEX specific_display_current_mappings_cache_13_14_tag_id_hash_id_index ON specific_display_current_mappings_cache_13_14 (tag_id, hash_id);
CREATE UNIQUE INDEX specific_display_pending_mappings_cache_13_14_tag_id_hash_id_index ON specific_display_pending_mappings_cache_13_14 (tag_id, hash_id);
CREATE TABLE specific_tags_cache_3_14 ( tag_id INTEGER PRIMARY KEY, namespace_id INTEGER, subtag_id INTEGER );
CREATE UNIQUE INDEX specific_tags_cache_3_14_namespace_id_subtag_id_index ON specific_tags_cache_3_14 (namespace_id, subtag_id);
CREATE INDEX specific_tags_cache_3_14_subtag_id_index ON specific_tags_cache_3_14 (subtag_id);
CREATE VIRTUAL TABLE specific_subtags_fts4_cache_3_14 USING fts4( subtag )
/* specific_subtags_fts4_cache_3_14(subtag) */;
CREATE TABLE IF NOT EXISTS 'specific_subtags_fts4_cache_3_14_content'(docid INTEGER PRIMARY KEY, 'c0subtag');
CREATE TABLE IF NOT EXISTS 'specific_subtags_fts4_cache_3_14_segments'(blockid INTEGER PRIMARY KEY, block BLOB);
CREATE TABLE IF NOT EXISTS 'specific_subtags_fts4_cache_3_14_segdir'(level INTEGER,idx INTEGER,start_block INTEGER,leaves_end_block INTEGER,end_block INTEGER,root BLOB,PRIMARY KEY(level, idx));
CREATE TABLE IF NOT EXISTS 'specific_subtags_fts4_cache_3_14_docsize'(docid INTEGER PRIMARY KEY, size BLOB);
CREATE TABLE IF NOT EXISTS 'specific_subtags_fts4_cache_3_14_stat'(id INTEGER PRIMARY KEY, value BLOB);
CREATE TABLE specific_integer_subtags_cache_3_14 ( subtag_id INTEGER PRIMARY KEY, integer_subtag INTEGER );
CREATE INDEX specific_integer_subtags_cache_3_14_integer_subtag_index ON specific_integer_subtags_cache_3_14 (integer_subtag);
CREATE TABLE specific_tags_cache_3_7 ( tag_id INTEGER PRIMARY KEY, namespace_id INTEGER, subtag_id INTEGER );
CREATE UNIQUE INDEX specific_tags_cache_3_7_namespace_id_subtag_id_index ON specific_tags_cache_3_7 (namespace_id, subtag_id);
CREATE INDEX specific_tags_cache_3_7_subtag_id_index ON specific_tags_cache_3_7 (subtag_id);
CREATE VIRTUAL TABLE specific_subtags_fts4_cache_3_7 USING fts4( subtag )
/* specific_subtags_fts4_cache_3_7(subtag) */;
CREATE TABLE IF NOT EXISTS 'specific_subtags_fts4_cache_3_7_content'(docid INTEGER PRIMARY KEY, 'c0subtag');
CREATE TABLE IF NOT EXISTS 'specific_subtags_fts4_cache_3_7_segments'(blockid INTEGER PRIMARY KEY, block BLOB);
CREATE TABLE IF NOT EXISTS 'specific_subtags_fts4_cache_3_7_segdir'(level INTEGER,idx INTEGER,start_block INTEGER,leaves_end_block INTEGER,end_block INTEGER,root BLOB,PRIMARY KEY(level, idx));
CREATE TABLE IF NOT EXISTS 'specific_subtags_fts4_cache_3_7_docsize'(docid INTEGER PRIMARY KEY, size BLOB);
CREATE TABLE IF NOT EXISTS 'specific_subtags_fts4_cache_3_7_stat'(id INTEGER PRIMARY KEY, value BLOB);
CREATE TABLE specific_integer_subtags_cache_3_7 ( subtag_id INTEGER PRIMARY KEY, integer_subtag INTEGER );
CREATE INDEX specific_integer_subtags_cache_3_7_integer_subtag_index ON specific_integer_subtags_cache_3_7 (integer_subtag);
CREATE TABLE specific_tags_cache_13_14 ( tag_id INTEGER PRIMARY KEY, namespace_id INTEGER, subtag_id INTEGER );
CREATE UNIQUE INDEX specific_tags_cache_13_14_namespace_id_subtag_id_index ON specific_tags_cache_13_14 (namespace_id, subtag_id);
CREATE INDEX specific_tags_cache_13_14_subtag_id_index ON specific_tags_cache_13_14 (subtag_id);
CREATE VIRTUAL TABLE specific_subtags_fts4_cache_13_14 USING fts4( subtag )
/* specific_subtags_fts4_cache_13_14(subtag) */;
CREATE TABLE IF NOT EXISTS 'specific_subtags_fts4_cache_13_14_content'(docid INTEGER PRIMARY KEY, 'c0subtag');
CREATE TABLE IF NOT EXISTS 'specific_subtags_fts4_cache_13_14_segments'(blockid INTEGER PRIMARY KEY, block BLOB);
CREATE TABLE IF NOT EXISTS 'specific_subtags_fts4_cache_13_14_segdir'(level INTEGER,idx INTEGER,start_block INTEGER,leaves_end_block INTEGER,end_block INTEGER,root BLOB,PRIMARY KEY(level, idx));
CREATE TABLE IF NOT EXISTS 'specific_subtags_fts4_cache_13_14_docsize'(docid INTEGER PRIMARY KEY, size BLOB);
CREATE TABLE IF NOT EXISTS 'specific_subtags_fts4_cache_13_14_stat'(id INTEGER PRIMARY KEY, value BLOB);
CREATE TABLE specific_integer_subtags_cache_13_14 ( subtag_id INTEGER PRIMARY KEY, integer_subtag INTEGER );
CREATE INDEX specific_integer_subtags_cache_13_14_integer_subtag_index ON specific_integer_subtags_cache_13_14 (integer_subtag);
CREATE TABLE specific_tags_cache_13_7 ( tag_id INTEGER PRIMARY KEY, namespace_id INTEGER, subtag_id INTEGER );
CREATE UNIQUE INDEX specific_tags_cache_13_7_namespace_id_subtag_id_index ON specific_tags_cache_13_7 (namespace_id, subtag_id);
CREATE INDEX specific_tags_cache_13_7_subtag_id_index ON specific_tags_cache_13_7 (subtag_id);
CREATE VIRTUAL TABLE specific_subtags_fts4_cache_13_7 USING fts4( subtag )
/* specific_subtags_fts4_cache_13_7(subtag) */;
CREATE TABLE IF NOT EXISTS 'specific_subtags_fts4_cache_13_7_content'(docid INTEGER PRIMARY KEY, 'c0subtag');
CREATE TABLE IF NOT EXISTS 'specific_subtags_fts4_cache_13_7_segments'(blockid INTEGER PRIMARY KEY, block BLOB);
CREATE TABLE IF NOT EXISTS 'specific_subtags_fts4_cache_13_7_segdir'(level INTEGER,idx INTEGER,start_block INTEGER,leaves_end_block INTEGER,end_block INTEGER,root BLOB,PRIMARY KEY(level, idx));
CREATE TABLE IF NOT EXISTS 'specific_subtags_fts4_cache_13_7_docsize'(docid INTEGER PRIMARY KEY, size BLOB);
CREATE TABLE IF NOT EXISTS 'specific_subtags_fts4_cache_13_7_stat'(id INTEGER PRIMARY KEY, value BLOB);
CREATE TABLE specific_integer_subtags_cache_13_7 ( subtag_id INTEGER PRIMARY KEY, integer_subtag INTEGER );
CREATE INDEX specific_integer_subtags_cache_13_7_integer_subtag_index ON specific_integer_subtags_cache_13_7 (integer_subtag);
CREATE TABLE combined_files_tags_cache_14 ( tag_id INTEGER PRIMARY KEY, namespace_id INTEGER, subtag_id INTEGER );
CREATE UNIQUE INDEX combined_files_tags_cache_14_namespace_id_subtag_id_index ON combined_files_tags_cache_14 (namespace_id, subtag_id);
CREATE INDEX combined_files_tags_cache_14_subtag_id_index ON combined_files_tags_cache_14 (subtag_id);
CREATE VIRTUAL TABLE combined_files_subtags_fts4_cache_14 USING fts4( subtag )
/* combined_files_subtags_fts4_cache_14(subtag) */;
CREATE TABLE IF NOT EXISTS 'combined_files_subtags_fts4_cache_14_content'(docid INTEGER PRIMARY KEY, 'c0subtag');
CREATE TABLE IF NOT EXISTS 'combined_files_subtags_fts4_cache_14_segments'(blockid INTEGER PRIMARY KEY, block BLOB);
CREATE TABLE IF NOT EXISTS 'combined_files_subtags_fts4_cache_14_segdir'(level INTEGER,idx INTEGER,start_block INTEGER,leaves_end_block INTEGER,end_block INTEGER,root BLOB,PRIMARY KEY(level, idx));
CREATE TABLE IF NOT EXISTS 'combined_files_subtags_fts4_cache_14_docsize'(docid INTEGER PRIMARY KEY, size BLOB);
CREATE TABLE IF NOT EXISTS 'combined_files_subtags_fts4_cache_14_stat'(id INTEGER PRIMARY KEY, value BLOB);
CREATE TABLE combined_files_integer_subtags_cache_14 ( subtag_id INTEGER PRIMARY KEY, integer_subtag INTEGER );
CREATE INDEX combined_files_integer_subtags_cache_14_integer_subtag_index ON combined_files_integer_subtags_cache_14 (integer_subtag);
CREATE TABLE combined_files_tags_cache_7 ( tag_id INTEGER PRIMARY KEY, namespace_id INTEGER, subtag_id INTEGER );
CREATE UNIQUE INDEX combined_files_tags_cache_7_namespace_id_subtag_id_index ON combined_files_tags_cache_7 (namespace_id, subtag_id);
CREATE INDEX combined_files_tags_cache_7_subtag_id_index ON combined_files_tags_cache_7 (subtag_id);
CREATE VIRTUAL TABLE combined_files_subtags_fts4_cache_7 USING fts4( subtag )
/* combined_files_subtags_fts4_cache_7(subtag) */;
CREATE TABLE IF NOT EXISTS 'combined_files_subtags_fts4_cache_7_content'(docid INTEGER PRIMARY KEY, 'c0subtag');
CREATE TABLE IF NOT EXISTS 'combined_files_subtags_fts4_cache_7_segments'(blockid INTEGER PRIMARY KEY, block BLOB);
CREATE TABLE IF NOT EXISTS 'combined_files_subtags_fts4_cache_7_segdir'(level INTEGER,idx INTEGER,start_block INTEGER,leaves_end_block INTEGER,end_block INTEGER,root BLOB,PRIMARY KEY(level, idx));
CREATE TABLE IF NOT EXISTS 'combined_files_subtags_fts4_cache_7_docsize'(docid INTEGER PRIMARY KEY, size BLOB);
CREATE TABLE IF NOT EXISTS 'combined_files_subtags_fts4_cache_7_stat'(id INTEGER PRIMARY KEY, value BLOB);
CREATE TABLE combined_files_integer_subtags_cache_7 ( subtag_id INTEGER PRIMARY KEY, integer_subtag INTEGER );
CREATE INDEX combined_files_integer_subtags_cache_7_integer_subtag_index ON combined_files_integer_subtags_cache_7 (integer_subtag);
CREATE TABLE combined_files_subtags_searchable_map_cache_14 ( subtag_id INTEGER PRIMARY KEY, searchable_subtag_id INTEGER );
CREATE INDEX combined_files_subtags_searchable_map_cache_14_searchable_subtag_id_index ON combined_files_subtags_searchable_map_cache_14 (searchable_subtag_id);
CREATE TABLE combined_files_subtags_searchable_map_cache_7 ( subtag_id INTEGER PRIMARY KEY, searchable_subtag_id INTEGER );
CREATE INDEX combined_files_subtags_searchable_map_cache_7_searchable_subtag_id_index ON combined_files_subtags_searchable_map_cache_7 (searchable_subtag_id);
CREATE TABLE specific_subtags_searchable_map_cache_3_14 ( subtag_id INTEGER PRIMARY KEY, searchable_subtag_id INTEGER );
CREATE INDEX specific_subtags_searchable_map_cache_3_14_searchable_subtag_id_index ON specific_subtags_searchable_map_cache_3_14 (searchable_subtag_id);
CREATE TABLE specific_subtags_searchable_map_cache_3_7 ( subtag_id INTEGER PRIMARY KEY, searchable_subtag_id INTEGER );
CREATE INDEX specific_subtags_searchable_map_cache_3_7_searchable_subtag_id_index ON specific_subtags_searchable_map_cache_3_7 (searchable_subtag_id);
CREATE TABLE specific_subtags_searchable_map_cache_13_14 ( subtag_id INTEGER PRIMARY KEY, searchable_subtag_id INTEGER );
CREATE INDEX specific_subtags_searchable_map_cache_13_14_searchable_subtag_id_index ON specific_subtags_searchable_map_cache_13_14 (searchable_subtag_id);
CREATE TABLE specific_subtags_searchable_map_cache_13_7 ( subtag_id INTEGER PRIMARY KEY, searchable_subtag_id INTEGER );
CREATE INDEX specific_subtags_searchable_map_cache_13_7_searchable_subtag_id_index ON specific_subtags_searchable_map_cache_13_7 (searchable_subtag_id);

client.db
CREATE TABLE services ( service_id INTEGER PRIMARY KEY AUTOINCREMENT, service_key BLOB_BYTES UNIQUE, service_type INTEGER, name TEXT, dictionary_string TEXT );
CREATE TABLE sqlite_sequence(name,seq);
CREATE TABLE alternate_file_groups ( alternates_group_id INTEGER PRIMARY KEY );
CREATE TABLE alternate_file_group_members ( alternates_group_id INTEGER, media_id INTEGER UNIQUE, PRIMARY KEY ( alternates_group_id, media_id ) );
CREATE TABLE analyze_timestamps ( name TEXT, num_rows INTEGER, timestamp INTEGER );
CREATE TABLE client_files_locations ( prefix TEXT, location TEXT );
CREATE TABLE ideal_client_files_locations ( location TEXT, weight INTEGER );
CREATE TABLE ideal_thumbnail_override_location ( location TEXT );
CREATE TABLE current_files ( service_id INTEGER, hash_id INTEGER, timestamp INTEGER, PRIMARY KEY ( service_id, hash_id ) );
CREATE TABLE deleted_files ( service_id INTEGER, hash_id INTEGER, PRIMARY KEY ( service_id, hash_id ) );
CREATE TABLE duplicate_files ( media_id INTEGER PRIMARY KEY, king_hash_id INTEGER UNIQUE );
CREATE TABLE duplicate_file_members ( media_id INTEGER, hash_id INTEGER UNIQUE, PRIMARY KEY ( media_id, hash_id ) );
CREATE TABLE duplicate_false_positives ( smaller_alternates_group_id INTEGER, larger_alternates_group_id INTEGER, PRIMARY KEY ( smaller_alternates_group_id, larger_alternates_group_id ) );
CREATE TABLE potential_duplicate_pairs ( smaller_media_id INTEGER, larger_media_id INTEGER, distance INTEGER, PRIMARY KEY ( smaller_media_id, larger_media_id ) );
CREATE TABLE confirmed_alternate_pairs ( smaller_media_id INTEGER, larger_media_id INTEGER, PRIMARY KEY ( smaller_media_id, larger_media_id ) );
CREATE TABLE local_file_deletion_reasons ( hash_id INTEGER PRIMARY KEY, reason_id INTEGER );
CREATE TABLE file_inbox ( hash_id INTEGER PRIMARY KEY );
CREATE TABLE files_info ( hash_id INTEGER PRIMARY KEY, size INTEGER, mime INTEGER, width INTEGER, height INTEGER, duration INTEGER, num_frames INTEGER, has_audio INTEGER_BOOLEAN, num_words INTEGER );
CREATE TABLE file_notes ( hash_id INTEGER, name_id INTEGER, note_id INTEGER, PRIMARY KEY ( hash_id, name_id ) );
CREATE TABLE file_transfers ( service_id INTEGER, hash_id INTEGER, PRIMARY KEY ( service_id, hash_id ) );
CREATE TABLE file_petitions ( service_id INTEGER, hash_id INTEGER, reason_id INTEGER, PRIMARY KEY ( service_id, hash_id, reason_id ) );
CREATE TABLE json_dict ( name TEXT PRIMARY KEY, dump BLOB_BYTES );
CREATE TABLE json_dumps ( dump_type INTEGER PRIMARY KEY, version INTEGER, dump BLOB_BYTES );
CREATE TABLE json_dumps_named ( dump_type INTEGER, dump_name TEXT, version INTEGER, timestamp INTEGER, dump BLOB_BYTES, PRIMARY KEY ( dump_type, dump_name, timestamp ) );
CREATE TABLE last_shutdown_work_time ( last_shutdown_work_time INTEGER );
CREATE TABLE local_ratings ( service_id INTEGER, hash_id INTEGER, rating REAL, PRIMARY KEY ( service_id, hash_id ) );
CREATE TABLE file_modified_timestamps ( hash_id INTEGER PRIMARY KEY, file_modified_timestamp INTEGER );
CREATE TABLE options ( options TEXT_YAML );
CREATE TABLE recent_tags ( service_id INTEGER, tag_id INTEGER, timestamp INTEGER, PRIMARY KEY ( service_id, tag_id ) );
CREATE TABLE remote_thumbnails ( service_id INTEGER, hash_id INTEGER, PRIMARY KEY( service_id, hash_id ) );
CREATE TABLE service_filenames ( service_id INTEGER, hash_id INTEGER, filename TEXT, PRIMARY KEY ( service_id, hash_id ) );
CREATE TABLE service_directories ( service_id INTEGER, directory_id INTEGER, num_files INTEGER, total_size INTEGER, note TEXT, PRIMARY KEY ( service_id, directory_id ) );
CREATE TABLE service_directory_file_map ( service_id INTEGER, directory_id INTEGER, hash_id INTEGER, PRIMARY KEY ( service_id, directory_id, hash_id ) );
CREATE TABLE service_info ( service_id INTEGER, info_type INTEGER, info INTEGER, PRIMARY KEY ( service_id, info_type ) );
CREATE TABLE statuses ( status_id INTEGER PRIMARY KEY, status TEXT UNIQUE );
CREATE TABLE tag_parents ( service_id INTEGER, child_tag_id INTEGER, parent_tag_id INTEGER, status INTEGER, PRIMARY KEY ( service_id, child_tag_id, parent_tag_id, status ) );
CREATE TABLE tag_parent_petitions ( service_id INTEGER, child_tag_id INTEGER, parent_tag_id INTEGER, status INTEGER, reason_id INTEGER, PRIMARY KEY ( service_id, child_tag_id, parent_tag_id, status ) );
CREATE TABLE tag_siblings ( service_id INTEGER, bad_tag_id INTEGER, good_tag_id INTEGER, status INTEGER, PRIMARY KEY ( service_id, bad_tag_id, status ) );
CREATE TABLE tag_sibling_petitions ( service_id INTEGER, bad_tag_id INTEGER, good_tag_id INTEGER, status INTEGER, reason_id INTEGER, PRIMARY KEY ( service_id, bad_tag_id, status ) );
CREATE TABLE url_map ( hash_id INTEGER, url_id INTEGER, PRIMARY KEY ( hash_id, url_id ) );
CREATE TABLE vacuum_timestamps ( name TEXT, timestamp INTEGER );
CREATE TABLE file_viewing_stats ( hash_id INTEGER PRIMARY KEY, preview_views INTEGER, preview_viewtime INTEGER, media_views INTEGER, media_viewtime INTEGER );
CREATE TABLE version ( version INTEGER );
CREATE TABLE yaml_dumps ( dump_type INTEGER, dump_name TEXT, dump TEXT_YAML, PRIMARY KEY ( dump_type, dump_name ) );
CREATE TABLE sqlite_stat1(tbl,idx,stat);
CREATE TABLE tag_sibling_application ( master_service_id INTEGER, service_index INTEGER, application_service_id INTEGER, PRIMARY KEY ( master_service_id, service_index ) );
CREATE TABLE tag_parent_application ( master_service_id INTEGER, service_index INTEGER, application_service_id INTEGER, PRIMARY KEY ( master_service_id, service_index ) );
CREATE INDEX current_files_timestamp_index ON current_files (timestamp);
CREATE UNIQUE INDEX duplicate_false_positives_larger_alternates_group_id_smaller_alternates_group_id_index ON duplicate_false_positives (larger_alternates_group_id, smaller_alternates_group_id);
CREATE UNIQUE INDEX potential_duplicate_pairs_larger_media_id_smaller_media_id_index ON potential_duplicate_pairs (larger_media_id, smaller_media_id);
CREATE UNIQUE INDEX confirmed_alternate_pairs_larger_media_id_smaller_media_id_index ON confirmed_alternate_pairs (larger_media_id, smaller_media_id);
CREATE INDEX files_info_size_index ON files_info (size);
CREATE INDEX files_info_mime_index ON files_info (mime);
CREATE INDEX files_info_width_index ON files_info (width);
CREATE INDEX files_info_height_index ON files_info (height);
CREATE INDEX files_info_duration_index ON files_info (duration);
CREATE INDEX files_info_num_frames_index ON files_info (num_frames);
CREATE INDEX file_notes_note_id_index ON file_notes (note_id);
CREATE INDEX file_transfers_hash_id_index ON file_transfers (hash_id);
CREATE INDEX file_petitions_hash_id_index ON file_petitions (hash_id);
CREATE INDEX local_ratings_hash_id_index ON local_ratings (hash_id);
CREATE INDEX local_ratings_rating_index ON local_ratings (rating);
CREATE INDEX file_modified_timestamps_file_modified_timestamp_index ON file_modified_timestamps (file_modified_timestamp);
CREATE INDEX url_map_url_id_index ON url_map (url_id);
CREATE INDEX file_viewing_stats_preview_views_index ON file_viewing_stats (preview_views);
CREATE INDEX file_viewing_stats_preview_viewtime_index ON file_viewing_stats (preview_viewtime);
CREATE INDEX file_viewing_stats_media_views_index ON file_viewing_stats (media_views);
CREATE INDEX file_viewing_stats_media_viewtime_index ON file_viewing_stats (media_viewtime);
CREATE INDEX current_files_hash_id_index ON current_files (hash_id);
CREATE INDEX deleted_files_hash_id_index ON deleted_files (hash_id);
CREATE INDEX file_notes_name_id_index ON file_notes (name_id);
CREATE INDEX service_filenames_hash_id_index ON service_filenames (hash_id);
CREATE INDEX service_directories_directory_id_index ON service_directories (directory_id);
CREATE INDEX service_directory_file_map_directory_id_index ON service_directory_file_map (directory_id);
CREATE INDEX service_directory_file_map_hash_id_index ON service_directory_file_map (hash_id);
CREATE INDEX tag_parents_service_id_parent_tag_id_index ON tag_parents (service_id, parent_tag_id);
CREATE INDEX tag_parent_petitions_service_id_parent_tag_id_index ON tag_parent_petitions (service_id, parent_tag_id);
CREATE INDEX tag_siblings_service_id_good_tag_id_index ON tag_siblings (service_id, good_tag_id);
CREATE INDEX tag_sibling_petitions_service_id_good_tag_id_index ON tag_sibling_petitions (service_id, good_tag_id);
CREATE TABLE repository_updates_13 ( update_index INTEGER, hash_id INTEGER, processed INTEGER_BOOLEAN, PRIMARY KEY ( update_index, hash_id ) );
CREATE INDEX repository_updates_13_hash_id_index ON repository_updates_13 (hash_id);
CREATE TABLE repository_updates_14 ( update_index INTEGER, hash_id INTEGER, processed INTEGER_BOOLEAN, PRIMARY KEY ( update_index, hash_id ) );
CREATE INDEX repository_updates_14_hash_id_index ON repository_updates_14 (hash_id);

client.mappings.db
CREATE TABLE current_mappings_7 ( tag_id INTEGER, hash_id INTEGER, PRIMARY KEY ( tag_id, hash_id ) ) WITHOUT ROWID;
CREATE TABLE deleted_mappings_7 ( tag_id INTEGER, hash_id INTEGER, PRIMARY KEY ( tag_id, hash_id ) ) WITHOUT ROWID;
CREATE TABLE pending_mappings_7 ( tag_id INTEGER, hash_id INTEGER, PRIMARY KEY ( tag_id, hash_id ) ) WITHOUT ROWID;
CREATE TABLE petitioned_mappings_7 ( tag_id INTEGER, hash_id INTEGER, reason_id INTEGER, PRIMARY KEY ( tag_id, hash_id ) ) WITHOUT ROWID;
CREATE TABLE sqlite_stat1(tbl,idx,stat);
CREATE UNIQUE INDEX current_mappings_7_hash_id_tag_id_index ON current_mappings_7 (hash_id, tag_id);
CREATE UNIQUE INDEX deleted_mappings_7_hash_id_tag_id_index ON deleted_mappings_7 (hash_id, tag_id);
CREATE UNIQUE INDEX pending_mappings_7_hash_id_tag_id_index ON pending_mappings_7 (hash_id, tag_id);
CREATE UNIQUE INDEX petitioned_mappings_7_hash_id_tag_id_index ON petitioned_mappings_7 (hash_id, tag_id);
CREATE TABLE current_mappings_14 ( tag_id INTEGER, hash_id INTEGER, PRIMARY KEY ( tag_id, hash_id ) ) WITHOUT ROWID;
CREATE UNIQUE INDEX current_mappings_14_hash_id_tag_id_index ON current_mappings_14 (hash_id, tag_id);
CREATE TABLE deleted_mappings_14 ( tag_id INTEGER, hash_id INTEGER, PRIMARY KEY ( tag_id, hash_id ) ) WITHOUT ROWID;
CREATE UNIQUE INDEX deleted_mappings_14_hash_id_tag_id_index ON deleted_mappings_14 (hash_id, tag_id);
CREATE TABLE pending_mappings_14 ( tag_id INTEGER, hash_id INTEGER, PRIMARY KEY ( tag_id, hash_id ) ) WITHOUT ROWID;
CREATE UNIQUE INDEX pending_mappings_14_hash_id_tag_id_index ON pending_mappings_14 (hash_id, tag_id);
CREATE TABLE petitioned_mappings_14 ( tag_id INTEGER, hash_id INTEGER, reason_id INTEGER, PRIMARY KEY ( tag_id, hash_id ) ) WITHOUT ROWID;
CREATE UNIQUE INDEX petitioned_mappings_14_hash_id_tag_id_index ON petitioned_mappings_14 (hash_id, tag_id);

client.master.db
CREATE TABLE hashes ( hash_id INTEGER PRIMARY KEY, hash BLOB_BYTES UNIQUE );
CREATE TABLE labels ( label_id INTEGER PRIMARY KEY, label TEXT UNIQUE );
CREATE TABLE local_hashes ( hash_id INTEGER PRIMARY KEY, md5 BLOB_BYTES, sha1 BLOB_BYTES, sha512 BLOB_BYTES );
CREATE TABLE namespaces ( namespace_id INTEGER PRIMARY KEY, namespace TEXT UNIQUE );
CREATE TABLE notes ( note_id INTEGER PRIMARY KEY, note TEXT UNIQUE );
CREATE TABLE subtags ( subtag_id INTEGER PRIMARY KEY, subtag TEXT UNIQUE );
CREATE TABLE tags ( tag_id INTEGER PRIMARY KEY, namespace_id INTEGER, subtag_id INTEGER );
CREATE TABLE texts ( text_id INTEGER PRIMARY KEY, text TEXT UNIQUE );
CREATE TABLE url_domains ( domain_id INTEGER PRIMARY KEY, domain TEXT UNIQUE );
CREATE TABLE urls ( url_id INTEGER PRIMARY KEY, domain_id INTEGER, url TEXT UNIQUE );
CREATE TABLE sqlite_stat1(tbl,idx,stat);
CREATE INDEX local_hashes_md5_index ON local_hashes (md5);
CREATE INDEX local_hashes_sha1_index ON local_hashes (sha1);
CREATE INDEX local_hashes_sha512_index ON local_hashes (sha512);
CREATE INDEX urls_domain_id_index ON urls (domain_id);
CREATE UNIQUE INDEX tags_namespace_id_subtag_id_index ON tags (namespace_id, subtag_id);
CREATE INDEX tags_subtag_id_index ON tags (subtag_id);
CREATE TABLE repository_hash_id_map_13 ( service_hash_id INTEGER PRIMARY KEY, hash_id INTEGER );
CREATE TABLE repository_tag_id_map_13 ( service_tag_id INTEGER PRIMARY KEY, tag_id INTEGER );
CREATE TABLE repository_hash_id_map_14 ( service_hash_id INTEGER PRIMARY KEY, hash_id INTEGER );
CREATE TABLE repository_tag_id_map_14 ( service_tag_id INTEGER PRIMARY KEY, tag_id INTEGER );
